#API REST

notification:
    type:         rest
    resource:     IDCI\Bundle\NotificationBundle\Controller\ApiNotificationController
    name_prefix:  api_notification_

notifier_configuration:
    type:         rest
    resource:     IDCI\Bundle\NotificationBundle\Controller\ApiNotifierConfigurationController
    name_prefix:  api_notifier_configuration_

notification_parameters:
    type:        rest
    resource:    IDCI\Bundle\NotificationBundle\Controller\ApiNotificationParametersController
    name_prefix: api_notification_parameters_
