tracking_history:
    resource: IDCI\Bundle\NotificationBundle\Controller\TrackingHistoryController
    type:     annotation

mirror_link:
    resource: IDCI\Bundle\NotificationBundle\Controller\MirrorLinkController
    type:     annotation
