<?php

namespace IDCI\Bundle\NotificationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationRepository 
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
    /**
     * Get Notification by status
     * @param type $status
     */
    public function getNotificationByStatus($status) {

        $result = $this->createQueryBuilder("n")   
            ->select('n')
            ->where('n.id = :id')
            ->setParameter('id', $status)
            ->getQuery()
            ->getArrayResult()
        ;

        return empty($result) ? array() : $result[0];
    }
    
    /**
     * Get Notification by type
     * @param type $type
     */
    public function getNotificationByType($type) {

        $result = $this
            ->createQueryBuilder("n")   
            ->select('n')
            ->where('n.id = :id')
            ->setParameter('id', $type)
            ->getQuery()
            ->getArrayResult()
        ;

        return empty($result) ? array() : $result[0];
    }

    /**
     * Get Notification by source
     * @param type $source
     */
    public function getNotificationBySource($source) {

        $result = $this
            ->createQueryBuilder("n")   
            ->select('n')
            ->where('n.id = :id')
            ->setParameter('id', $source)
            ->getQuery()
            ->getArrayResult()
        ;

        return empty($result) ? array() : $result[0];
    }
    
    /**
     * Get Notification between two created_at dates
     */
    public function getNotificationBetweenTwoDates() {
        $dateNow = new DateTime();
        $result = $this
            ->createQueryBuilder("n")
            ->select('n')
            ->where('n.id = :id')
            ->andWhere('')
            ->getQuery()
            ->getArrayResult()
        ;

        return empty($result) ? array() : $result[0];
    }

    /**
     * Get Notification between two updated_at dates
     */
    public function getNotificationBetweenTwoUpdateDates() {
        $dateNow = new DateTime();
        $result = $this
             ->createQueryBuilder("n")   
             ->select('n')
             ->where('n.id = :id')                
             ->getQuery()
             ->getArrayResult()
        ;

        return empty($result) ? array() : $result[0];
    }
}
