<?php

namespace IDCI\Bundle\NotificationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationRepository 
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
    /**
     * Get Notifications by status
     *
     * @param string $status
     * @return Notification
     */
    public function getNotificationsByStatus($status)
    {
        $result = $this
            ->createQueryBuilder("n")
            ->where('n.status = :status')
            ->setParameter('status', $status)
            ->getQuery()
            ->getResult()
        ;

        return empty($result) ? array() : $result;
    }

    /**
     * Get Notifications by type
     *
     * @param string $type
     * @return Notification
     */
    public function getNotificationsByType($type)
    {
        $result = $this
            ->createQueryBuilder("n")
            ->where('n.type = :type')
            ->setParameter('type', $type)
            ->getQuery()
            ->getResult()
        ;

        return empty($result) ? array() : $result;
    }

    /**
     * Get Notifications by source
     *
     * @param string $source
     * @return Notification
     */
    public function getNotificationsBySource($source)
    {
        $result = $this
            ->createQueryBuilder("n")
            ->where('n.source = :source')
            ->setParameter('source', $source)
            ->getQuery()
            ->getResult()
        ;

        return empty($result) ? array() : $result;
    }
    
    /**
     * Get Notifications between two created_at dates
     *
     * @return Notification
     */
    public function getNotificationsBetweenTwoDates()
    {
        $dateNow = new DateTime();
        $result = $this
            ->createQueryBuilder("n")
            ->where('n.id = :id')
            ->getQuery()
            ->getArrayResult()
        ;

        return empty($result) ? array() : $result;
    }

    /**
     * Get Notifications between two updated_at dates
     *
     * @return Notification
     */
    public function getNotificationsBetweenTwoUpdatedDates()
    {
        $dateNow = new DateTime();
        $result = $this
             ->createQueryBuilder("n")
             ->where('n.id = :id')
             ->getQuery()
             ->getArrayResult()
        ;

        return empty($result) ? array() : $result;
    }
}
