<?php

namespace IDCI\Bundle\NotificationBundle\Entity\Repository;

/**
 * TrackingHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackingHistoryRepository extends \Doctrine\ORM\EntityRepository
{
    
}
